version: '2'

services:
  web:
    build: .
    ports:
      - "8080:80"
    depends_on: 
      - db
    environment:
          DatabaseServer: "db"
          DatabaseName: "EMPRESTIMO"
          DatabaseUser: "teste"
          DatabaseUserPassword: "Test1234"
  db:
    image: "microsoft/mssql-server-linux:2017-CU4"
    ports: 
      - "1433"
    environment: 
      SA_PASSWORD: "Test1234"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
      MSSQL_DB: "EMPRESTIMO"
      MSSQL_USER: "teste"
      MSSQL_PASSWORD: "Test1234"